### ISSUE TITLE
Polling architecture

### ISSUE THREAD

**Issue by w1zeman1p** [tyrauber/sec_query#12]
This is meant to be more of a discussion and place to gather thoughts about how to build out the polling architecture.
From skype:
Already in existence are
Entity, Filing, Transaction, Relationship

If we were to build out as a rails app from the perspective of the SEC:
```rb
resources :entities do
  resources :relationships
end
resources :filings do
  resources :transactions
  get 'recent/:type' # types like form4, 10k, 14g
end
```

Modeling each of these objects in ruby is easy.
Building the objects to abstract interaction with the SECs disparate site is the hard part.

There are really 3 ways to pull down data.
1.  pulling down info about a known entity (works great and is complete)
2.  pulling down recent fillings as links, then pulling down each raw form and parsing
3.  pulling down ALL past filings as links, then pulling down each raw form and parsing

The current structure I propose is:
```rb
FilingGateway
   # will hit http://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&output=atom
   # and deal with pagination to yield to the block each Filing object
  ::fetch_recent(limit = 10000, &blk)
  # will use something like eventmachine and will hit the feed every 30 seconds fetching
  # whatever filings that haven't been fetched (use some cache with the url to check Moneta maybe?)
  #  yield to the block each new filing that is found
  ::poll(wait = 30, &blk) # wait in seconds
  #  will hit ftp server and download zipped index of filings for that day, unzip them and yield Filing objects to the block as they are processed
  ::fetch_day(date, &blk)
  # will hit ftp server and download zipped index of filings for that quarter, unzip them and yield Filing objects to the block as they are processed
  ::fetch_quarter(year, quarter, &blk) # 1994 - 2014, 1-4
```

Add method in `SecURI` which takes a filing object and figures out where the raw .txt file is... probably something like `SecURI::uri_for(filing)`

**Comment by tyrauber** [comment]
@w1zeman1p Closing. Feel free to reopen if you want to work on this.
