### ISSUE TITLE
Document parsing

### ISSUE THREAD

**Issue by w1zeman1p** [tyrauber/sec_query#15]
Starting to think about how to parse the documents and pros and cons of using Hpricot and Nokogiri.

I found a bunch of xsd files that can be used to validate the xml from ownership documents and I can only assume there is some if not full coverage of the other document types as well.

After playing with Nokogiris XML and XSD stuff I've concluded that its pretty easy to validate the XML with XSD with something like:

```rb
require 'nokogiri'
schema =  Nokogiri::XML::Schema(IO.read('ownership4Document.xsd.xml'))
doc = Nokogiri::XML(IO.read('doc4.xml'))
p schema.validate(doc)
```

these xsd files are from the zip file here https://www.sec.gov/info/edgar/ownershipxmltechspec.htm

**Comment by tyrauber** [comment]
Already done? Reopen if not.
