### ISSUE TITLE
Documentation is out of date?

### ISSUE THREAD

**Issue by msalvi123** [tyrauber/sec_query#34]
SecQuery::Entity.find only accepts one argument in version 1.1.0

>SecQuery::Entity.find("AAPL", true, true, true)
  ArgumentError: wrong number of arguments (4 for 1)

def self.find(entity_args) version 1.0.6  to 1.1.0

def self.find(entity_args, *options) version 1.0.5

**Comment by tyrauber** [comment]
So sorry, this was missed and the delay in responding.  The documentation has been updated in #36.  Thank you for reporting this.
