### ISSUE TITLE
ActionView::Template::Error (undefined method `[]' for nil:NilClass):

### ISSUE THREAD

**Issue by philiplindblom** [tyrauber/sec_query#41]
Hi,

When querying companies on smaller stockexchanges, I'm unable to query them based on anything else than SIC number.

I'm currently using the gem stock_quotes as well, and I'd like to be able to pull the data from SEC based on a symbol, which I then can parse to @name (company name) and query that against SEC.

The error I get is 

ActionView::Template::Error (undefined method `[]' for nil:NilClass):

Is there a way I could get CIK from @stock_quote.sic ?

Because there are huge discrepancies  when searching for name. For some stocks "Name Inc" works. For others only "Name" works and for others "Ticker" works. So getting CIK from @stock.symbol would be fantastic.

I'd be so thankful for any replies.

**Comment by tyrauber** [comment]
Hi @philiplindblom, the StockQuote gem uses Yahoo's financial api to get quotes, and unfortunately doesn't return an SEC CIK. The only unique identifier you'll get from StockQuote responses is the Stock Symbol.

Your best bet is to not use name at all - as you said, there is a lot of variance there in syntax - and solely use the Symbol, which both StockQuote and SecQuery use.

```
quote = StockQuote::Stock.quote("aapl")
entity = SecQuery::Entity.find("aapl")
```

Regarding the error, can you post the code that resulted in that?  There should be a more friendly error message there.

**Comment by philiplindblom** [comment]
Indeed Ty.

The problem is that some stocks, especially stocks from smaller stock exchanges in the US are not searchable via the Ticker on SEC.

**Comment by tyrauber** [comment]
Interesting. Hadn't experienced that before. Can you give me some examples? (name, symbol, sic)

**Comment by philiplindblom** [comment]
EXOL, NPWZ, ANLDF. All listed on the OTC and are not queryable via Ticker through SEC.
