### ISSUE TITLE
SecQuery::Entity.find(query) offset?

### ISSUE THREAD

**Issue by maxiedaniels** [tyrauber/sec_query#43]
I'm experimenting with `SecQuery::Entity.find("AAPL").filings` for example, however I'm only ever returning 80 filings when I do this. Is there an undocumented way to offset the query, so I can retrieve more than 80 results?

**Comment by tyrauber** [comment]
For more control over pagination of filings use the Filing class directly.
```
SecQuery::Filing.find('AAPL', START, LIMIT)
```
Looks like entity.filings is a convenience method hard coded to the last 80 filings.
